import math

"""
OBJECTIVE METHOD FOR THE OPTIMIZER
FEEL FREE TO REPLACE WITH ANY METHOD OF CHOICE

(NOTE: THE DESIGNED ALGORITHM PASSES THE N-DIMENSIONAL VECTOR AS
AN INPUT TO THE OBJECTIVE FUNCTION, AND TAKES OUTPUT AS A NUMERICAL VALUE.
YOU CAN CHANGE IT TO BEHAVE DIFFERENTLY BASED ON YOUR REQUIREMENTS.
)
"""

def objective(item):
	"""
	THE OBJECTIVE FUNCTION -- BY DEFAULT THE SUM OF VALUES
	(CAN BE CHANGED TO ANYTHING OF CHOICE)
	"""
	return sum(item)